import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { Trash2, AlertCircle } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface ValidationResult {
  puzzle: { start: string; goal: string; wordLength: number };
  valid: boolean;
  reason?: string;
  minDistance?: number;
  pathCount?: number;
}

interface Props {
  validationResults: ValidationResult[];
  onCleanupComplete: () => void;
}

export function PuzzleVaultCleaner({ validationResults, onCleanupComplete }: Props) {
  const { toast } = useToast();
  const [cleaning, setCleaning] = useState(false);

  const cleanupPuzzles = async () => {
    setCleaning(true);
    try {
      const failedCount = validationResults.filter(r => !r.valid).length;
      
      if (failedCount === 0) {
        toast({
          title: "No Failed Puzzles",
          description: "All puzzles passed validation!",
        });
        setCleaning(false);
        return;
      }

      // Separate valid puzzles by word length with actual validated min distances
      const valid4L = validationResults
        .filter(r => r.valid && r.puzzle.wordLength === 4)
        .map(r => ({ start: r.puzzle.start, goal: r.puzzle.goal, minDist: r.minDistance || 3 }));
      
      const valid5L = validationResults
        .filter(r => r.valid && r.puzzle.wordLength === 5)
        .map(r => ({ start: r.puzzle.start, goal: r.puzzle.goal, minDist: r.minDistance || 3 }));
      
      const valid6L = validationResults
        .filter(r => r.valid && r.puzzle.wordLength === 6)
        .map(r => ({ start: r.puzzle.start, goal: r.puzzle.goal, minDist: r.minDistance || 3 }));

      // Generate cleaned file contents
      const content4L = `// Curated 4-Letter Daily Puzzle Pairs (${valid4L.length} Valid Puzzles)
// All puzzles validated for solvability, acceptance gates, and minimum 3-move requirement
// Generated by algorithm validation on ${new Date().toISOString().split('T')[0]}

export interface CuratedPuzzlePair {
  start: string;
  goal: string;
  minDist?: number;
}

export const CURATED_4L_PUZZLES: CuratedPuzzlePair[] = [
${valid4L.map(p => `  { start: "${p.start}", goal: "${p.goal}", minDist: ${p.minDist} },`).join('\n')}
];
`;

      const content5L = `// Curated 5-Letter Daily Puzzle Pairs (${valid5L.length} Valid Puzzles)
// All puzzles validated for solvability, acceptance gates, and minimum 3-move requirement
// Generated by algorithm validation on ${new Date().toISOString().split('T')[0]}

export interface CuratedPuzzlePair {
  start: string;
  goal: string;
  minDist?: number;
}

export const CURATED_5L_PUZZLES: CuratedPuzzlePair[] = [
${valid5L.map(p => `  { start: "${p.start}", goal: "${p.goal}", minDist: ${p.minDist} },`).join('\n')}
];
`;

      const content6L = `// Curated 6-Letter Daily Puzzle Pairs (${valid6L.length} Valid Puzzles)
// All puzzles validated for solvability, acceptance gates, and minimum 3-move requirement
// Generated by algorithm validation on ${new Date().toISOString().split('T')[0]}

export interface CuratedPuzzlePair {
  start: string;
  goal: string;
  minDist?: number;
}

export const CURATED_6L_PUZZLES: CuratedPuzzlePair[] = [
${valid6L.map(p => `  { start: "${p.start}", goal: "${p.goal}", minDist: ${p.minDist} },`).join('\n')}
];
`;

      // Store to localStorage for the developer to copy
      localStorage.setItem('cleaned_4L_puzzles', content4L);
      localStorage.setItem('cleaned_5L_puzzles', content5L);
      localStorage.setItem('cleaned_6L_puzzles', content6L);

      // Download files as well
      const downloadFile = (content: string, filename: string) => {
        const blob = new Blob([content], { type: 'text/typescript' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      };

      downloadFile(content4L, 'curatedPuzzles4L.ts');
      downloadFile(content5L, 'curatedPuzzles5L.ts');
      downloadFile(content6L, 'curatedPuzzles6L.ts');

      const totalValid = valid4L.length + valid5L.length + valid6L.length;

      toast({
        title: "Cleaned Files Ready",
        description: `Removed ${failedCount} failed puzzles. ${totalValid} valid puzzles remain. Files downloaded and saved to localStorage.`,
      });

      onCleanupComplete();

    } catch (error: any) {
      console.error('Cleanup error:', error);
      toast({
        title: "Cleanup Failed",
        description: error.message,
        variant: "destructive"
      });
    } finally {
      setCleaning(false);
    }
  };

  const failedCount = validationResults.filter(r => !r.valid).length;
  const validCount = validationResults.filter(r => r.valid).length;

  if (failedCount === 0) return null;

  return (
    <Card className="p-6 border-red-500/50">
      <div className="space-y-4">
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            <strong>{failedCount} puzzles failed validation</strong> and need to be removed.
            {validCount} puzzles passed and will be kept.
          </AlertDescription>
        </Alert>

        <div className="flex items-start gap-4">
          <div className="p-3 bg-red-500/10 rounded-lg">
            <Trash2 className="h-6 w-6 text-red-500" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-semibold mb-2">Clean Puzzle Files</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Click below to download cleaned versions of all three curated puzzle files.
              These files will contain only the {validCount} valid puzzles that passed all algorithm checks.
            </p>
            <div className="space-y-2">
              <Button 
                onClick={cleanupPuzzles}
                disabled={cleaning}
                variant="destructive"
                className="w-full"
              >
                {cleaning ? (
                  <>Processing...</>
                ) : (
                  <>
                    <Trash2 className="mr-2 h-4 w-4" />
                    Download Cleaned Files ({validCount} valid puzzles)
                  </>
                )}
              </Button>
              <p className="text-xs text-muted-foreground text-center">
                After download, replace the files in src/lib/ and refresh the page
              </p>
            </div>
          </div>
        </div>
      </div>
    </Card>
  );
}

